/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/BookingScreen`; params?: Router.UnknownInputParams; } | { pathname: `/BookingSummary`; params?: Router.UnknownInputParams; } | { pathname: `/FavoriteScreen`; params?: Router.UnknownInputParams; } | { pathname: `/forgetPassword`; params?: Router.UnknownInputParams; } | { pathname: `/HomePage`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/paymentOption`; params?: Router.UnknownInputParams; } | { pathname: `/paymentSuccess`; params?: Router.UnknownInputParams; } | { pathname: `/ProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/savePassword`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/TurfBooking`; params?: Router.UnknownInputParams; } | { pathname: `/TurfView`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/BookingScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/BookingSummary`; params?: Router.UnknownOutputParams; } | { pathname: `/FavoriteScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/forgetPassword`; params?: Router.UnknownOutputParams; } | { pathname: `/HomePage`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/paymentOption`; params?: Router.UnknownOutputParams; } | { pathname: `/paymentSuccess`; params?: Router.UnknownOutputParams; } | { pathname: `/ProfileScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/savePassword`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/TurfBooking`; params?: Router.UnknownOutputParams; } | { pathname: `/TurfView`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/BookingScreen${`?${string}` | `#${string}` | ''}` | `/BookingSummary${`?${string}` | `#${string}` | ''}` | `/FavoriteScreen${`?${string}` | `#${string}` | ''}` | `/forgetPassword${`?${string}` | `#${string}` | ''}` | `/HomePage${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/paymentOption${`?${string}` | `#${string}` | ''}` | `/paymentSuccess${`?${string}` | `#${string}` | ''}` | `/ProfileScreen${`?${string}` | `#${string}` | ''}` | `/savePassword${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/TurfBooking${`?${string}` | `#${string}` | ''}` | `/TurfView${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/BookingScreen`; params?: Router.UnknownInputParams; } | { pathname: `/BookingSummary`; params?: Router.UnknownInputParams; } | { pathname: `/FavoriteScreen`; params?: Router.UnknownInputParams; } | { pathname: `/forgetPassword`; params?: Router.UnknownInputParams; } | { pathname: `/HomePage`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/paymentOption`; params?: Router.UnknownInputParams; } | { pathname: `/paymentSuccess`; params?: Router.UnknownInputParams; } | { pathname: `/ProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/savePassword`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/TurfBooking`; params?: Router.UnknownInputParams; } | { pathname: `/TurfView`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
